config/routes.rb
ContactManager::Application.routes.draw do
  root to: 'site#index'

  match "/login" => redirect("/auth/twitter"), as: :login, via: :get
  delete "/logout" => "sessions#destroy", as: :logout

  get '/auth/:provider/callback' => 'sessions#create'
  resources :companies

  resources :email_addresses, :except => [:index, :show]

  resources :phone_numbers, :except => [:index, :show]

  resources :people

end

app/models/company.rb
class Company < ActiveRecord::Base
	validates :name, presence: true
	has_many :phone_numbers, as: :contact
	has_many :email_addresses, as: :contact

	def to_s
		"#{name}"
	end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render action: 'show', status: :created, location: @company }
      else
        format.html { render action: 'new' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name)
    end
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Edit <%= @company.name %></h1>

<%= render 'form' %>

<ul class="actions">
	<li><%= link_to 'Show', @company %></li>
	<li><%= link_to 'Back', companies_path %></li>
</ul>

app/views/companies/index.html.haml
%h1 Listing companies

%table
  %tr
    %th Name
    %th

- @companies.each do |company| 
  %tr
    %td= company 
    %td
      %ul.actions
        %li= link_to 'Show', company 
        %li= link_to 'Edit', edit_company_path(company) 
        %li= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } 

%br

=link_to 'New Company', new_company_path, id: "new_company"  
| 
=link_to 'Go Home', root_path 

app/views/companies/new.html.haml
%h1 New company
= render 'form'
= link_to 'Back', companies_path

app/views/companies/show.html.erb
<div class="company">	
	<p id="notice"><%= notice %></p>

	<h1>
	  <%= @company.name %>
	</h1>

	<%= render 'phone_numbers/phone_numbers', :phone_numbers => @company.phone_numbers %>

	<%= render 'email_addresses/email_addresses', :email_addresses => @company.email_addresses %>

	<ul class="actions">
		<li><%= link_to 'Add phone number', new_phone_number_path(contact_id: @company.id, contact_type: 'Company') %></li> 
		<li><%= link_to 'Add email address', new_email_address_path(contact_id: @company.id, contact_type: 'Company') %></li>
		<li><%= link_to 'Edit', edit_company_path(@company) %></li>
		<li><%= link_to 'Back', companies_path %></li>
	</ul>
</div>