config/routes.rb
ContactManager::Application.routes.draw do
  root to: 'site#index'

  match "/login" => redirect("/auth/twitter"), as: :login, via: :get
  delete "/logout" => "sessions#destroy", as: :logout

  get '/auth/:provider/callback' => 'sessions#create'
  resources :companies

  resources :email_addresses, :except => [:index, :show]

  resources :phone_numbers, :except => [:index, :show]

  resources :people

end

app/controllers/email_addresses_controller.rb
class EmailAddressesController < ApplicationController
  before_action :set_email_address, only: [:edit, :update, :destroy]

  # GET /email_addresses/new
  def new
    @email_address = EmailAddress.new(contact_id: params[:contact_id], contact_type: params[:contact_type])
  end

  # GET /email_addresses/1/edit
  def edit
  end

  # POST /email_addresses
  # POST /email_addresses.json
  def create
    @email_address = EmailAddress.new(email_address_params)

    respond_to do |format|
      if @email_address.save
        format.html { redirect_to @email_address.contact, notice: 'Email address was successfully created.' }
        format.json { render action: 'show', status: :created, location: @email_address }
      else
        format.html { render action: 'new' }
        format.json { render json: @email_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /email_addresses/1
  # PATCH/PUT /email_addresses/1.json
  def update
    respond_to do |format|
      if @email_address.update(email_address_params)
        format.html { redirect_to @email_address.contact, notice: 'Email address was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @email_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /email_addresses/1
  # DELETE /email_addresses/1.json
  def destroy
    @email_address.destroy
    respond_to do |format|
      format.html { redirect_to @email_address.contact, notice: 'Email address was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_email_address
      @email_address = EmailAddress.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def email_address_params
      params.require(:email_address).permit(:address, :contact_id, :contact_type)
    end
end

app/views/email_addresses/_email_addresses.html.erb
<h4>Email Addresses</h4>
<% if email_addresses.exists? %>
<ul>
	<% email_addresses.each do |email| %>
		<li><%= email.address %> <%= link_to('Edit Address', edit_email_address_path(email)) %> <%= link_to "Delete Address", email_address_path(email), method: :delete %></li>
	<% end %>
</ul>
<% else %>
<p>No email addresses yet.</p>
<% end %>

app/views/email_addresses/_form.html.erb
<%= form_for(@email_address) do |f| %>
  <% if @email_address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@email_address.errors.count, "error") %> prohibited this email_address from being saved:</h2>

      <ul>
      <% @email_address.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.hidden_field :contact_id %>
  </div>
  <div class="field">
    <%= f.hidden_field :contact_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/email_addresses/edit.html.erb
<h1>Editing email_address</h1>

<%= render 'form' %>
<!-- 
<%= link_to 'Show', @email_address %> | -->
<%= link_to 'Back', @email_address.contact %>

app/views/email_addresses/new.html.erb
<h1>New Email Address for <%= @email_address.contact %></h1>

<%= render 'form' %>

<%= link_to 'Back', @email_address.contact %>